AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  SourceCodeBucketName:
    Description: "The name of the S3 bucket that contains the lambda definition"
    Type: "String"
  SourceCodeZip:
    Description: "The name of the zip file contains the code for the lambda function"
    Type: "String"

Outputs:
  GetAllWalletsLambdaArn:
    Value: !GetAtt "GetAllWalletsLambda.Arn"
  GetWalletByIdLambdaArn:
    Value: !GetAtt "GetWalletByIdLambda.Arn"    
  MineCoinLambdaArn:
    Value: !GetAtt "MineCoinLambda.Arn"
    
Resources:
  DinkumCoinLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
          Action:
          - sts:AssumeRole
      Policies:
        - PolicyName: LambdaLogPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
            - Effect: Allow
              Action:
              - logs:CreateLogGroup
              - logs:CreateLogStream
              - logs:PutLogEvents
              Resource: "*"
  
  GetAllWalletsLambda:
    Type: AWS::Lambda::Function
    Properties:
      Description: Lambda function for fetching all dinkumcoin wallets
      Handler: DinkumCoin.Wallet.Lambda::DinkumCoin.Wallet.Lambda.Function::GetWallets
      FunctionName: DinkumCoin-GetAllWalletsLambdaFunction
      Runtime: dotnetcore1.0
      MemorySize: 128
      Timeout: 300
      Code:
        S3Bucket:
          !Ref "SourceCodeBucketName"
        S3Key: 
          !Ref "SourceCodeZip"
      Role: 
        Fn::GetAtt:
        - DinkumCoinLambdaRole
        - Arn
   
  GetWalletByIdLambda:
    Type: AWS::Lambda::Function
    Properties:
      Description: Lambda function for fetching a specific wallet
      Handler: DinkumCoin.Wallet.Lambda::DinkumCoin.Wallet.Lambda.Function::GetWallet
      FunctionName: DinkumCoin-GetWalletByIdLambdaFunction
      Runtime: dotnetcore1.0 
      MemorySize: 128
      Timeout: 300
      Code:
        S3Bucket:
          !Ref "SourceCodeBucketName"
        S3Key: 
          !Ref "SourceCodeZip"
      Role:       
        Fn::GetAtt:
        - DinkumCoinLambdaRole
        - Arn
        
  MineCoinLambda:
    Type: AWS::Lambda::Function
    Properties:
      Description: Lambda function for attempting to mine a new coin
      Handler: DinkumCoin.Wallet.Lambda::DinkumCoin.Wallet.Lambda.Function::MineCoin
      FunctionName: DinkumCoin-MineCoinLambdaFuntion
      Runtime: dotnetcore1.0
      MemorySize: 128
      Timeout: 300
      Code:
        S3Bucket:
          !Ref "SourceCodeBucketName"
        S3Key: 
          !Ref "SourceCodeZip"
      Role: 
        Fn::GetAtt:
        - DinkumCoinLambdaRole
        - Arn     
